import Artikel from './Artikel';
import Schuhe from './Schuhe';
import Verwaltung from './Verwaltung';
var artikel1 = new Artikel('Jeans', 'Asos Jeans', 139, 0);
console.log(artikel1);
var artikel2 = new Artikel('Pulli', 'Asos Pulli', 49, 39);
console.log(artikel2);
var artikel3 = new Schuhe('Schuhe', 'Nike Schuhe', 129, 0, 42, 'Nike');
console.log(artikel3);
var artikel4 = new Schuhe('Schuhe', 'Adidas Schuhe', 79, 0, 39, 'Adidas');
console.log(artikel4);
var verwaltung = new Verwaltung();
verwaltung.addArtikelsToList(artikel1, artikel2, artikel3, artikel4);
console.log(verwaltung.listArticles());
verwaltung.deleteArtikelsToList(artikel1);
console.log(verwaltung.listArticles());
console.log("TEST2dff");
